import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Home/Sidebar/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Go India Stocks Task",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
              <Sidebar>
              {children}
              </Sidebar>
              </body>
        </html>
    );
}
